//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.14 at 06:16:21 PM CST 
//


package edu.phema.knime.ihe.svs.jaxb;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for ObservationLivingExpenseValue.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ObservationLivingExpenseValue">
 *   &lt;restriction base="{urn:ihe:iti:svs:2008}cs">
 *     &lt;enumeration value="LIVEXP"/>
 *     &lt;enumeration value="CLOTH"/>
 *     &lt;enumeration value="FOOD"/>
 *     &lt;enumeration value="HEALTH"/>
 *     &lt;enumeration value="HOUSE"/>
 *     &lt;enumeration value="LEGAL"/>
 *     &lt;enumeration value="MORTG"/>
 *     &lt;enumeration value="RENT"/>
 *     &lt;enumeration value="SUNDRY"/>
 *     &lt;enumeration value="TRANS"/>
 *     &lt;enumeration value="UTIL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ObservationLivingExpenseValue {

    LIVEXP,
    CLOTH,
    FOOD,
    HEALTH,
    HOUSE,
    LEGAL,
    MORTG,
    RENT,
    SUNDRY,
    TRANS,
    UTIL;

    public String value() {
        return name();
    }

    public static ObservationLivingExpenseValue fromValue(String v) {
        return valueOf(v);
    }

}
