//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.14 at 06:16:21 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ihe:iti:svs:2008", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.phema.knime.ihe.svs.jaxb;
