//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.14 at 06:16:21 PM CST 
//


package edu.phema.ihe.svs.jaxb;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for PatientImportance.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PatientImportance">
 *   &lt;restriction base="{urn:ihe:iti:svs:2008}cs">
 *     &lt;enumeration value="BM"/>
 *     &lt;enumeration value="FD"/>
 *     &lt;enumeration value="FOR"/>
 *     &lt;enumeration value="GOVT"/>
 *     &lt;enumeration value="DFM"/>
 *     &lt;enumeration value="SFM"/>
 *     &lt;enumeration value="STF"/>
 *     &lt;enumeration value="DR"/>
 *     &lt;enumeration value="VIP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum PatientImportance {

    BM,
    FD,
    FOR,
    GOVT,
    DFM,
    SFM,
    STF,
    DR,
    VIP;

    public String value() {
        return name();
    }

    public static PatientImportance fromValue(String v) {
        return valueOf(v);
    }

}
